# Generated by Django 4.2.13 on 2024-06-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_crop_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='sample_photo',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
