# Generated by Django 4.2.13 on 2024-07-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_test_sample_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='sample_photo',
            field=models.TextField(),
        ),
    ]
